# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: false
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 16.0
org_name: Odoo Community Association (OCA)
org_slug: em230418
rebel_module_groups: []
repo_description: null
repo_name: Do not install this addons
repo_slug: ispanski-styd-addons
repo_website: https://github.com/em230418/ispanski-styd-addons
travis_apt_packages: []
travis_apt_sources: []

